apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gnp6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gnp6
    app.kubernetes.io/part-of: tkrw-pr712-0075-0027-app
  name: devfile-sample-gnp6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gnp6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gnp6
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-gnp6@sha256:d20e1d93ca20dba5f9601a6c0f304b3180d9d37285d9c47a4a53563225986c7b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
