apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gnp6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-gnp6@sha256:d20e1d93ca20dba5f9601a6c0f304b3180d9d37285d9c47a4a53563225986c7b
        name: my-nodejs
        resources: {}
status: {}
